"""Создание таблицы user

Revision ID: 0a9dadb40c4d
Revises:
Create Date: 2025-07-06 13:27:14.132987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a9dadb40c4d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "NR_USER",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nickname", sa.String(length=30), nullable=False),
        sa.Column("password", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_NR_USER_nickname"), "NR_USER", ["nickname"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_NR_USER_nickname"), table_name="NR_USER")
    op.drop_table("NR_USER")
    # ### end Alembic commands ###
