"""изменил название столбца

Revision ID: ef11bc016871
Revises: 0a9dadb40c4d
Create Date: 2025-07-06 17:02:15.142435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef11bc016871'
down_revision: Union[str, Sequence[str], None] = '0a9dadb40c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NR_USER', sa.Column('username', sa.String(length=30), nullable=False))
    op.drop_index(op.f('ix_NR_USER_nickname'), table_name='NR_USER')
    op.create_index(op.f('ix_NR_USER_username'), 'NR_USER', ['username'], unique=True)
    op.drop_column('NR_USER', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NR_USER', sa.Column('nickname', sa.VARCHAR(length=30), nullable=False))
    op.drop_index(op.f('ix_NR_USER_username'), table_name='NR_USER')
    op.create_index(op.f('ix_NR_USER_nickname'), 'NR_USER', ['nickname'], unique=1)
    op.drop_column('NR_USER', 'username')
    # ### end Alembic commands ###
